### ISSUE TITLE
Trouble with dependencies

### ISSUE THREAD

**Issue by Dreamlone** [ITMO-NSS-team/BAMT#12]
## Trouble with Python versions
Made a copy of the framework repo. Create venv with with the specified requirements.txt
When launch `experiments/fedot_bn_example.py` got the following error 

```
ImportError: cannot import name 'TypedDict' from 'typing' (C:\Users\558\AppData\Local\Programs\Python\Python37\lib\typing.py)
```

According to this [issue](https://github.com/python/typeshed/issues/3500) the problem is probably with the version of Python I am using. Anyway, when I used venv on python 3.9 instead of 3.7, it worked.

## Dependencies may be incomplete
You use FEDOT (I understand that it is now used in experimental mode) in your experiments, as well as packages such as pgmpy, gmr, pyvis. However, they are not specified in requirements.txt. It may be worth expanding the list of libraries 

Please check my worries

**Comment by Roman223** [comment]
Hello Dreamlone,
Thanks for your report. 

We decided to convert framework to PyPi package to let users download it with pip. 
Therefore any problem with comitability of BAMT and version of python will be solved with PyPi solution, hot fix for this is already done and will be released in near several days.

List of dependencies includes only packages for stable version of BAMT. 

Experiments including FEDOT framework is being tested, and code related to this is in old logic of BAMT, so it is unstable. 
When it is rewrited, it will be added to dependencies.

**Comment by Dreamlone** [comment]
@Roman223, Thank you so much for the clarification

I get your argument about the package manager. But what if I am a developer who wants to use your source code for modifications. Or I want to install a version not from PYPi but from github repo. Perhaps in this case it is worth adding a section to the readme that explains how I can install all the necessary libraries

Obviously, not all libraries can be installed with the command "pip install -r requirements.txt"

**Comment by nicl-nno** [comment]
Is this issue still actual?

**Comment by Dreamlone** [comment]
I think we can mark the issue as closed

**Comment by ManuelSchneid3r** [comment]
Nothing suspicous in the logs. i cant reproduce this on noble https://termbin.com/kfup . have to try a jammy vm
