### ISSUE TITLE
set_structure doesn't work with ContinuousBN

### ISSUE THREAD

**Issue by Anaxagor** [ITMO-NSS-team/BAMT#13]
When I create a continuous network with the use_mixture=true flag and want to set a structure to it with set_structure(), after that the node types don't change, and the parents don't update either. I am attaching code and dataset.
[Code.txt](https://github.com/ITMO-NSS-team/BAMT/files/8451104/Code.txt)
[synth_data.csv](https://github.com/ITMO-NSS-team/BAMT/files/8451105/synth_data.csv)

**Comment by Roman223** [comment]
Hello Anaxagor,

Set_structure method accepts nodes as first argument. Setter has misunderstood your list of tuples, so just replace `true_net` to `edges=true_net`. 

We will add message for log when such errors occur.
