### ISSUE TITLE
Duplicating code

### ISSUE THREAD

**Issue by nicl-nno** [ITMO-NSS-team/BAMT#32]
Некоторые части кода довольно сильно повторяют соседние.

Вот тут, например, явно можно вынести общую часть:

![image](https://user-images.githubusercontent.com/5711814/218581087-f6cf3fdb-413c-4112-92ca-a14306c96dd3.png)

**Comment by jrzkaminski** [comment]
Конкретно этот случай дублирования исправлен, плюс парочка других

**Comment by nicl-nno** [comment]
Можно сразу в PR-ах отмечать связанные issue, чтобы они автоматически закрывались.
