### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by nicl-nno** [ITMO-NSS-team/BAMT#35]
Текущее README не особо понятно новичку. 

Project structure написано очень скупо, Oil and Gas Reservoirs Parameters Analysis выглядит вообще непонятно (это кейс, или функциональность, или что-то ещё?). Очень не хватает примеров использования.

У нас ещё нет готового образа README, но можно посмотреть на черновик тут (https://github.com/ITMO-NSS-team/open-source-ops/pull/12/files) или опереться на FEDOT-овский.

**Comment by jrzkaminski** [comment]
Readme обновлен

**Comment by nicl-nno** [comment]
Выглядит здорово! 

Для Citation я бы одну конкретную "главную" статью выбрал - которую хотели бы, чтобы цитировали. >1 все равно никто не будет ставить.
